spring:
  application:
    name: ystar-id-generate-provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.224.188.112:8808/ystar_common?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: 123456

dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: nacos://139.224.188.112:8848
  protocol:
    name: dubbo
    port: 9098